---
workers: 6
istart:  0 # used for starting at predefined index of batch list if previously incomplete
cpt:

  averse: {'b': 0.0, 'lam': 2.25, 'eta_p': 0.88, 'eta_n': 1.0, 'delta_p': 0.61, 'delta_n': 0.69,'mean_value_ref': True}
  neutral: {'b': 0.0, 'lam': 1.0, 'eta_p': 1.0, 'eta_n': 1.0, 'delta_p': 1.0, 'delta_n': 1.0,'mean_value_ref': False}
  seeking: { 'b': 0.0, 'lam': 0.44, 'eta_p': 1.0, 'eta_n': 0.88, 'delta_p': 0.61, 'delta_n': 0.69,'mean_value_ref': True }

jobs:
  risky_coordination_ring:
    agents: ['averse','neutral','seeking']
    p_slips: ['default'] # can manually specify
    set: # sets misc. config parameters for all other jobs
      time_cost: -0.3 # rational does 0.6

  risky_multipath:
    agents: [ 'averse','neutral','seeking' ]
    p_slips: [ 'default' ] # can manually specify
    set: # sets misc. config parameters for all other jobs
      time_cost: -0.3 # rational does 0.6